version: '3.9'

networks:
  my-network:
    driver: bridge

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - task-service
    networks:
      - my-network

  user-service:
    build:
      context: ./user-service
    ports:
      - "50051:50051"
    networks:
      - my-network

  task-service: 
    build:
      context: ./task-service
    ports:
      - "4000:4000"
    networks:
      - my-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - my-network

volumes:
  mongo-data:
